# Generated by Django 5.2.11 on 2026-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0034_auto_20200512_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcategory',
            name='name_de',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='groupcategory',
            name='name_es',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='groupcategory',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='groupcategory',
            name='name_it',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='groupcategory',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='description_it',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='description_pt',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='title_de',
            field=models.CharField(max_length=1000, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='title_es',
            field=models.CharField(max_length=1000, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='title_fr',
            field=models.CharField(max_length=1000, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='title_it',
            field=models.CharField(max_length=1000, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='title_pt',
            field=models.CharField(max_length=1000, null=True, verbose_name='Title'),
        ),
    ]
