# Generated by Django 5.2.11 on 2026-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0056_alter_service_password_alter_service_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_de',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_es',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_fr',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_it',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_pt',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
