# Generated by Django 3.2.20 on 2024-05-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0040_auto_20240108_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadparallelismlimit',
            name='max_number',
            field=models.PositiveSmallIntegerField(default=5, help_text='The maximum number of parallel uploads (0 to 32767).'),
        ),
    ]
