# Generated by Django 4.2.9 on 2024-07-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0042_alter_uploadparallelismlimit_max_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadparallelismlimit",
            name="max_number",
            field=models.PositiveSmallIntegerField(
                default=5, help_text="The maximum number of parallel uploads (0 to 32767)."
            ),
        ),
    ]
