# Generated by Django 5.2.11 on 2026-02-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0044_alter_uploadparallelismlimit_max_number'),
        ('upload', '0053_drop_celery_results_tables'),
    ]

    operations = [
    ]
