# Generated by Django 5.2.11 on 2026-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0095_alter_configuration_id_alter_contactrole_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='description_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='license_text_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='license_text_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='license_text_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='license_text_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='license_text_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='name_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restrictioncodetype',
            name='description_de',
            field=models.TextField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restrictioncodetype',
            name='description_es',
            field=models.TextField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restrictioncodetype',
            name='description_fr',
            field=models.TextField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restrictioncodetype',
            name='description_it',
            field=models.TextField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restrictioncodetype',
            name='description_pt',
            field=models.TextField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restrictioncodetype',
            name='gn_description_de',
            field=models.TextField(max_length=255, null=True, verbose_name='GeoNode description'),
        ),
        migrations.AddField(
            model_name='restrictioncodetype',
            name='gn_description_es',
            field=models.TextField(max_length=255, null=True, verbose_name='GeoNode description'),
        ),
        migrations.AddField(
            model_name='restrictioncodetype',
            name='gn_description_fr',
            field=models.TextField(max_length=255, null=True, verbose_name='GeoNode description'),
        ),
        migrations.AddField(
            model_name='restrictioncodetype',
            name='gn_description_it',
            field=models.TextField(max_length=255, null=True, verbose_name='GeoNode description'),
        ),
        migrations.AddField(
            model_name='restrictioncodetype',
            name='gn_description_pt',
            field=models.TextField(max_length=255, null=True, verbose_name='GeoNode description'),
        ),
        migrations.AddField(
            model_name='spatialrepresentationtype',
            name='description_de',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spatialrepresentationtype',
            name='description_es',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spatialrepresentationtype',
            name='description_fr',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spatialrepresentationtype',
            name='description_it',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spatialrepresentationtype',
            name='description_pt',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spatialrepresentationtype',
            name='gn_description_de',
            field=models.CharField(max_length=255, null=True, verbose_name='GeoNode description'),
        ),
        migrations.AddField(
            model_name='spatialrepresentationtype',
            name='gn_description_es',
            field=models.CharField(max_length=255, null=True, verbose_name='GeoNode description'),
        ),
        migrations.AddField(
            model_name='spatialrepresentationtype',
            name='gn_description_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='GeoNode description'),
        ),
        migrations.AddField(
            model_name='spatialrepresentationtype',
            name='gn_description_it',
            field=models.CharField(max_length=255, null=True, verbose_name='GeoNode description'),
        ),
        migrations.AddField(
            model_name='spatialrepresentationtype',
            name='gn_description_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='GeoNode description'),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='description_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='description_es',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='description_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='description_it',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='description_pt',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='gn_description_de',
            field=models.TextField(default='', null=True, verbose_name='GeoNode description'),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='gn_description_es',
            field=models.TextField(default='', null=True, verbose_name='GeoNode description'),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='gn_description_fr',
            field=models.TextField(default='', null=True, verbose_name='GeoNode description'),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='gn_description_it',
            field=models.TextField(default='', null=True, verbose_name='GeoNode description'),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='gn_description_pt',
            field=models.TextField(default='', null=True, verbose_name='GeoNode description'),
        ),
    ]
