# Generated by Django 3.2.13 on 2022-04-28 07:32
import json
from django.db import migrations, connections


def migrate_map_data_blob_forward(apps, schema_editor):
    # We can't import the Map model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    Map = apps.get_model('maps', 'Map')
    ResourceBase = apps.get_model('base', 'ResourceBase')
    for map in Map.objects.all():
        # We can't use map.resourcebase_ptr, we need to explicitly retrieve the resourcebase
        resourcebase = ResourceBase.objects.get(id=map.resourcebase_ptr_id)
        # mapstore2_adapter does not exist anymore as an app. So we need raw sql to get the blob from the old table.
        sql_string = f'SELECT blob from mapstore2_adapter_mapstoredata where resource_id={map.resourcebase_ptr_id};'
        with connections['default'].cursor() as cursor:
            cursor.execute(sql_string)
            result = cursor.fetchall()
            if result:
                resourcebase.blob = json.loads(result[0][0])
                resourcebase.save()


def migrate_map_data_blob_reverse(apps, schema_editor):
    # We can't import the Map model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    Map = apps.get_model('maps', 'Map')
    ResourceBase = apps.get_model('base', 'ResourceBase')
    for map in Map.objects.all():
        # We can't use map.resourcebase_ptr, we need to explicitly retrieve the resourcebase
        resourcebase = ResourceBase.objects.get(id=map.resourcebase_ptr_id)
        resourcebase.blob = dict()
        resourcebase.save()


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0042_remove_maplayer_styles'),
    ]

    operations = [
        migrations.RunPython(migrate_map_data_blob_forward, migrate_map_data_blob_reverse),
    ]
