# Generated by Django 5.2.11 on 2026-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0044_alter_maplayer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='abstract_de',
            field=models.TextField(blank=True, help_text='brief narrative summary of the content of the resource(s)', max_length=2000, null=True, verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='map',
            name='abstract_es',
            field=models.TextField(blank=True, help_text='brief narrative summary of the content of the resource(s)', max_length=2000, null=True, verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='map',
            name='abstract_fr',
            field=models.TextField(blank=True, help_text='brief narrative summary of the content of the resource(s)', max_length=2000, null=True, verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='map',
            name='abstract_it',
            field=models.TextField(blank=True, help_text='brief narrative summary of the content of the resource(s)', max_length=2000, null=True, verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='map',
            name='abstract_pt',
            field=models.TextField(blank=True, help_text='brief narrative summary of the content of the resource(s)', max_length=2000, null=True, verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='map',
            name='constraints_other_de',
            field=models.TextField(blank=True, help_text='other restrictions and legal prerequisites for accessing and using the resource or metadata', null=True, verbose_name='restrictions other'),
        ),
        migrations.AddField(
            model_name='map',
            name='constraints_other_es',
            field=models.TextField(blank=True, help_text='other restrictions and legal prerequisites for accessing and using the resource or metadata', null=True, verbose_name='restrictions other'),
        ),
        migrations.AddField(
            model_name='map',
            name='constraints_other_fr',
            field=models.TextField(blank=True, help_text='other restrictions and legal prerequisites for accessing and using the resource or metadata', null=True, verbose_name='restrictions other'),
        ),
        migrations.AddField(
            model_name='map',
            name='constraints_other_it',
            field=models.TextField(blank=True, help_text='other restrictions and legal prerequisites for accessing and using the resource or metadata', null=True, verbose_name='restrictions other'),
        ),
        migrations.AddField(
            model_name='map',
            name='constraints_other_pt',
            field=models.TextField(blank=True, help_text='other restrictions and legal prerequisites for accessing and using the resource or metadata', null=True, verbose_name='restrictions other'),
        ),
        migrations.AddField(
            model_name='map',
            name='data_quality_statement_de',
            field=models.TextField(blank=True, help_text="general explanation of the data producer's knowledge about the lineage of a dataset", max_length=2000, null=True, verbose_name='data quality statement'),
        ),
        migrations.AddField(
            model_name='map',
            name='data_quality_statement_es',
            field=models.TextField(blank=True, help_text="general explanation of the data producer's knowledge about the lineage of a dataset", max_length=2000, null=True, verbose_name='data quality statement'),
        ),
        migrations.AddField(
            model_name='map',
            name='data_quality_statement_fr',
            field=models.TextField(blank=True, help_text="general explanation of the data producer's knowledge about the lineage of a dataset", max_length=2000, null=True, verbose_name='data quality statement'),
        ),
        migrations.AddField(
            model_name='map',
            name='data_quality_statement_it',
            field=models.TextField(blank=True, help_text="general explanation of the data producer's knowledge about the lineage of a dataset", max_length=2000, null=True, verbose_name='data quality statement'),
        ),
        migrations.AddField(
            model_name='map',
            name='data_quality_statement_pt',
            field=models.TextField(blank=True, help_text="general explanation of the data producer's knowledge about the lineage of a dataset", max_length=2000, null=True, verbose_name='data quality statement'),
        ),
        migrations.AddField(
            model_name='map',
            name='purpose_de',
            field=models.TextField(blank=True, help_text='summary of the intentions with which the resource(s) was developed', max_length=500, null=True, verbose_name='purpose'),
        ),
        migrations.AddField(
            model_name='map',
            name='purpose_es',
            field=models.TextField(blank=True, help_text='summary of the intentions with which the resource(s) was developed', max_length=500, null=True, verbose_name='purpose'),
        ),
        migrations.AddField(
            model_name='map',
            name='purpose_fr',
            field=models.TextField(blank=True, help_text='summary of the intentions with which the resource(s) was developed', max_length=500, null=True, verbose_name='purpose'),
        ),
        migrations.AddField(
            model_name='map',
            name='purpose_it',
            field=models.TextField(blank=True, help_text='summary of the intentions with which the resource(s) was developed', max_length=500, null=True, verbose_name='purpose'),
        ),
        migrations.AddField(
            model_name='map',
            name='purpose_pt',
            field=models.TextField(blank=True, help_text='summary of the intentions with which the resource(s) was developed', max_length=500, null=True, verbose_name='purpose'),
        ),
        migrations.AddField(
            model_name='map',
            name='supplemental_information_de',
            field=models.TextField(default='No information provided', help_text='any other descriptive information about the dataset', max_length=2000, null=True, verbose_name='supplemental information'),
        ),
        migrations.AddField(
            model_name='map',
            name='supplemental_information_es',
            field=models.TextField(default='No information provided', help_text='any other descriptive information about the dataset', max_length=2000, null=True, verbose_name='supplemental information'),
        ),
        migrations.AddField(
            model_name='map',
            name='supplemental_information_fr',
            field=models.TextField(default='No information provided', help_text='any other descriptive information about the dataset', max_length=2000, null=True, verbose_name='supplemental information'),
        ),
        migrations.AddField(
            model_name='map',
            name='supplemental_information_it',
            field=models.TextField(default='No information provided', help_text='any other descriptive information about the dataset', max_length=2000, null=True, verbose_name='supplemental information'),
        ),
        migrations.AddField(
            model_name='map',
            name='supplemental_information_pt',
            field=models.TextField(default='No information provided', help_text='any other descriptive information about the dataset', max_length=2000, null=True, verbose_name='supplemental information'),
        ),
        migrations.AddField(
            model_name='map',
            name='title_de',
            field=models.CharField(help_text='name by which the cited resource is known', max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='map',
            name='title_es',
            field=models.CharField(help_text='name by which the cited resource is known', max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='map',
            name='title_fr',
            field=models.CharField(help_text='name by which the cited resource is known', max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='map',
            name='title_it',
            field=models.CharField(help_text='name by which the cited resource is known', max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='map',
            name='title_pt',
            field=models.CharField(help_text='name by which the cited resource is known', max_length=255, null=True, verbose_name='title'),
        ),
    ]
